### ISSUE TITLE
Unable to log into Production 

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#11] opened 2017-05-04 22:14 UTC
I tried again to get into production  with no luck.  I was able to the log on page and enter the Production Access Code. When I tried it in IE I get the error message that cannot find page.  I tried it in chrome and I get unauthorized.

Guy Trimarchi
Los Angeles County

**Comment by david-sanabria** [comment] 2017-05-04 23:15
DevOps Engineering is reviewing this issue.

**Comment by monte-williams** [comment] 2017-05-04 23:17
I think I figured out the problem.  It seems that when I saved the link as a favorite in IE it does not work, but if I just paste in the link into  IE it works.  

Guy Trimarchi

**Comment by david-sanabria** [comment] 2017-05-04 23:19
Issue identified by user; no error to investigate. Closing the issue.

**Closed by david-sanabria** 2017-05-04 23:19 UTC
Labels: bug, Production-Impact

**Comment by david-sanabria** [comment] 2017-05-04 23:25
Root Cause of this issue was that the end user created a bookmark that brought them directly to part of the application they should not have been in. I will pass this back to the UI developers as feedback to see if there is anything they can do to mitigate this kind of error in the future. 

Separately, I suggest that the implementation team take note of this and add it to some kind of user awareness item. Users can bookmark the base application URL (i.e. https://sandbox.cwds.ca.gov/ ), and can edit their bookmarks even after creating them to replace the text with this URL.
