### ISSUE TITLE
Sandbox Crashes upon click "submit" in I.E. (LA)

### ISSUE THREAD

**Issue by monte-williams** [ca-cwds/devops#10] opened 2017-04-27 16:22 UTC
## Issue Description
In Internet Explorer, once "submit" was clicked the screen refreshed with a message - "Service Temporarily Unavailable". 

## Business Impact
Sandbox - Impacts ability to do user testing. 

## Date/Time of first occurrence
2017-04-27 

## Is the Issue Repeatable?
Unsure

**Comment by michaelsampath** [comment] 2017-05-04 20:01
Issue is around traffic routes getting routed between two availability zones and in the process the session / token might be getting dropped. Currently, we are shutting down one availability zone to see whether the issue gets resolved. We will monitor the services for couple of days till we are able to coe up with a root cause analysis and a fix for high availability (HA).

**Comment by david-sanabria** [comment] 2017-05-09 18:30
Some network changes were made that appear to have contributed to, or caused, this issue last week. After investigating the root cause of this issue, it appears that the cause of related to changing the network address of some key servers caused this issue. After restarting dependent services, the new network addresses were picked up and operated normally.

Additional testing was done on Saturday, May 06, which showed that services were operating normally after a clean startup. All subsequent, observed behavior indicates that the root issue was successfully identified and mitigated.

**Comment by david-sanabria** [comment] 2017-05-09 18:31
@monte-williams Can you please confirm that this issue has been resolved and we can close this ticket?

**Comment by monte-williams** [comment] 2017-05-09 18:49
Issue is not currently happening. Good to close.

**Comment by david-sanabria** [comment] 2017-05-24 17:18
Issue confirmed as `resolved`

**Closed by david-sanabria** 2017-05-24 17:18 UTC
Labels: bug, duplicate, Fixed, Network-Related, Non-Prod-Impact, Root Cause Identified
